const { PutObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

const s3Client = require("./s3Client");

/**
 * Generates a pre-signed S3 upload URL for raw audio files.
 *
 * Canonical path format (must not change):
 * district-001/raw-audio/{applicationId}/{timestamp}-{random}.wav
 *
 * @param {string} fileKey - Canonical S3 key generated by s3KeyGenerator.generateAudioKey
 * @returns {Promise<string>} Signed S3 upload URL
 */
const generateUploadUrl = async (fileKey) => {
  const bucketName = process.env.S3_BUCKET;

  if (!bucketName) {
    throw new Error("S3_BUCKET environment variable is required");
  }

  if (!fileKey || typeof fileKey !== "string") {
    throw new Error("fileKey is required to generate upload URL");
  }

  const command = new PutObjectCommand({
    Bucket: bucketName,
    Key: fileKey,
    ContentType: "audio/wav",
  });

  const uploadUrl = await getSignedUrl(s3Client, command, {
    expiresIn: 60,
  });

  return uploadUrl;
};

module.exports = {
  generateUploadUrl,
};
